### ISSUE TITLE
Images don't resize in Media pane

### ISSUE THREAD

**Issue by githamm** [denverpost/gametracker#16]
It'll probably never happen in real life, but if you're in the Media pane and resize the window the images don't respond too nicely ... a Media Center issue I imagine
![gametracker](https://cloud.githubusercontent.com/assets/6498109/9950313/8089c49e-5d76-11e5-890a-0099edb4dcc6.png)
![gametracker-2](https://cloud.githubusercontent.com/assets/6498109/9950339/c398b39e-5d76-11e5-875a-d6717ed1f643.png)

**Comment by schneidan** [comment]
This behavior is a problem with media center embeds, not the Gametracker.
