### ISSUE TITLE
Add support to for Perform sports videos

### ISSUE THREAD

**Issue by danielboniface** [denverpost/gametracker#17]
Add the ability to embed videos from Perform (aka Sporting News). We are able to create embeddable playlists in our Perform video dashboard with game highlights, previews and more.

Here is an example of a perform embed code:

<script src="http://player.performgroup.com/eplayer.js#8e9a31ae9c16de0a8f08f89580.11hrrvnxxgcho15mv6dsnvd13y.d" async></script>

**Comment by danielboniface** [comment]
<script src="http://player.performgroup.com/eplayer.js#8e9a31ae9c16de0a8f08f89580.11hrrvnxxgcho15mv6dsnvd13y.d" async></script>

**Comment by schneidan** [comment]
I didn't get the embed code example. Can you paste it in again with three graves before and after (the backwards apostrophe on the key to the left of the "1" key)?

**Comment by schneidan** [comment]
This is done.
