### ISSUE TITLE
Specific game scoreboards/stats are not updating until a few minutes before game time

### ISSUE THREAD

**Issue by danielboniface** [denverpost/gametracker#18]
I suspect the issue is with sportsdirect xml feed latency, but I could be wrong.

**Comment by schneidan** [comment]
Actually, it looks like it's a combination of two things -- one I have control over and one I'll need to get Jeff Howell's help with. I hope to have this fixed Friday (#fingerscrossed)

**Comment by schneidan** [comment]
Think this is working now.
