### ISSUE TITLE
No ads

### ISSUE THREAD

**Issue by freejoe76** [denverpost/gametracker#19]

**Comment by schneidan** [comment]
There are ad tags, but there's almost never anything to load into them... I suppose I could tack on a cube ad under the live blog/media/etc. Not sure how valid it would be if I loaded 5 cubes and none ever got seen. Suggestions?

**Comment by freejoe76** [comment]
I viewed source on http://gametracker.denverpost.com/broncos/ and I didn't see the ad tags, correct me if I'm wrong.

**Comment by schneidan** [comment]
Well then. Yep, they were turned off. I turned them back on.

**Comment by freejoe76** [comment]
Can you turn them on everywhere? I don't see them on http://gametracker.denverpost.com/cu/ http://gametracker.denverpost.com/ http://gametracker.denverpost.com/csu/ http://gametracker.denverpost.com/avs/ http://gametracker.denverpost.com/nuggets/

**Comment by schneidan** [comment]
Yeah, definitely. I remember there being a reason they were off on one of them, but it was a long time ago and I can't remember why, so let's just turn them all on.

Did you have any other ad ideas? I think adding a cube below the content of each of the 5 content 'tabs' might work, but I'm thinking it might have to kind of be dynamic? If a given reader never looks at the Stats tab, it's pretty disingenuous to load an ad there, right? I'm thinking it might be time to do away with the 'sliding' behavior and rewrite the JS for those tabs to just swap the content in the main div. Would probably lighten the loads a bit, and definitely be easy to do things like dynamically loading an ad.

Thoughts?

**Comment by freejoe76** [comment]
I like the one-long-page idea, it moves away from hiding the content under tabs.

**Comment by schneidan** [comment]
I fear that people don't scroll to the end of the things we have now, so I'm not sure they'd ever get to the next thing. Or you mean stack them up and the buttons just scroll down to the next one? That would probably work better than the current swipe-sideways version ... and could dynamically insert ads between them. But not sure how to deal with the couple things that are iframed ... currently the iframes are just ridiculously long so the end never cuts off...

**Comment by freejoe76** [comment]
Yea, stack 'em up and let the buttons do the scroll. Put ads in between.

**Comment by schneidan** [comment]
I'll have to do that in the next update...

**Comment by freejoe76** [comment]
I don't see any ad tags on gametracker today.

**Comment by schneidan** [comment]
Found a bug that was turning ads back off when you tried to save other changes with ads already enabled and previously saved. Fixed.
